/* Task collaboration UI. API contract is documented in COLLABORATION_FRONTEND_API.md. */
(function () {
  'use strict';
  var state = { page: 1, pages: 1, limit: 20, total: 0, items: [], current: null, user: {}, regions: [], transition: null, requestId: 0, due: '', discussionRead: false, editorFiles: [], discussionFiles: [], editorClientTaskId: null, discussionClientMessageId: null, discussionDraftSignature: null };
  var STATUS = { new:'Yangi', in_progress:'Jarayonda', blocked:'Bloklangan', done:'Bajarilgan', cancelled:'Bekor qilingan', archived:'Arxivlangan' };
  var BADGE = { new:'warning', in_progress:'info', blocked:'error', done:'success', cancelled:'neutral', archived:'neutral' };
  function el(id) { return document.getElementById(id); }
  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
  function list(v) { return Array.isArray(v) ? v : []; }
  function names(v, fallback) { var a = list(v).map(function(x){ return typeof x === 'string' ? x : (x.full_name || x.name || x.email || x.code); }).filter(Boolean); return a.length ? a.join(', ') : (fallback || '—'); }
  function date(v) { if (!v) return '—'; var d = new Date(v); return isNaN(d.getTime()) ? String(v) : d.toLocaleString(); }
  function localDate(v) { if (!v) return ''; var d = new Date(v); if (isNaN(d.getTime())) return ''; return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16); }
  function size(bytes) { var value=Number(bytes||0);if(value<1024)return value+' B';if(value<1048576)return(value/1024).toFixed(1)+' KB';return(value/1048576).toFixed(1)+' MB'; }
  function toast(message, type) { var n=el('cmsToast'); if(!n)return; n.textContent=message; n.className='cms-toast cms-toast--'+(type||'info')+' show'; setTimeout(function(){n.classList.remove('show');},4000); }
  function close(id) { if (window.AdminModal) AdminModal.close(id); }
  function open(id, opener) { if (window.AdminModal) AdminModal.open(id, opener); }
  function selected(container) { return Array.prototype.map.call(container.querySelectorAll('input:checked'),function(i){return Number(i.value)||i.value;}); }
  function uuid() { var c=window.crypto||window.msCrypto;if(c&&c.randomUUID)return c.randomUUID();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(ch){var r=c&&c.getRandomValues?c.getRandomValues(new Uint8Array(1))[0]&15:Math.floor(Math.random()*16),v=ch==='x'?r:(r&3|8);return v.toString(16);}); }
  function query() {
    var sort=el('taskSort').value.split('_'),direction=sort.pop(),field=sort.join('_');
    if(field==='due')field='due_at';
    if(field==='created')field='created_at';
    var p = new URLSearchParams({ page:String(state.page), limit:String(state.limit), sort:field, direction:direction });
    [['q','taskQuery'],['status','taskStatus']].forEach(function(x){var v=el(x[1]).value.trim();if(v)p.set(x[0],v);});
    if(state.due)p.set('due',state.due);
    return p.toString();
  }
  function renderKpis(k) { k=k||{}; el('taskKpiOpen').textContent=Number(k.new_count||0)+Number(k.in_progress_count||0)+Number(k.blocked_count||0); el('taskKpiOverdue').textContent=k.overdue_count||0; el('taskKpiBlocked').textContent=k.blocked_count||0; el('taskKpiDone').textContent=k.done_count||0; }
  function taskRegions(t) { return list(t.regions).length ? t.regions : (t.assigned_region_code ? [t.assigned_region_code] : []); }
  function allowedTransitions(t) { if (list(t.allowed_actions).indexOf('transition') === -1) return []; var m={new:['in_progress','cancelled'],in_progress:['blocked','done','cancelled'],blocked:['in_progress','cancelled'],done:['in_progress'],cancelled:['new']};return m[t.status]||[]; }
  function renderRows() {
    var body=el('tasksTableRows');
    if(!state.items.length){body.innerHTML='<tr class="u-empty-row"><td colspan="6" role="status">Topshiriq topilmadi.</td></tr>';return;}
    body.innerHTML=state.items.map(function(t){
      var actions=allowedTransitions(t).slice(0,2).map(function(a){return '<button type="button" class="btn btn--sm btn--secondary" data-transition="'+esc(a)+'" data-task="'+esc(t.id)+'">'+esc(STATUS[a]||a)+'</button>';}).join(' ');
      return '<tr><td>#'+esc(t.id)+'</td><td><button class="task-link" type="button" data-task-open="'+esc(t.id)+'">'+esc(t.title)+'</button></td><td>'+esc(names(taskRegions(t)))+'</td><td>'+esc(date(t.due_at))+(t.due_state==='overdue'?' <span class="badge badge--error">Kechikdi</span>':'')+'</td><td><span class="badge badge--'+(BADGE[t.status]||'neutral')+'">'+esc(STATUS[t.status]||t.status)+'</span></td><td><button type="button" class="btn btn--sm btn--secondary" data-task-open="'+esc(t.id)+'">Ko‘rish</button> '+actions+'</td></tr>';
    }).join('');
  }
  function loadTasks() {
    var id=++state.requestId, body=el('tasksTableRows'); body.setAttribute('aria-busy','true'); el('taskListStatus').textContent='Yuklanmoqda...';
    return NgoApi.get('/admin/tasks?'+query()).then(function(res){ if(id!==state.requestId)return; state.items=list(res.items);state.total=Number(res.total||state.items.length);state.pages=Number(res.pages||Math.max(1,Math.ceil(state.total/state.limit)));if(state.page>state.pages){state.page=state.pages;return loadTasks();}renderRows();renderKpis(res.kpis);el('taskTotal').textContent=state.total+' ta';el('taskPageInfo').textContent=state.page+' / '+state.pages;el('taskPrev').disabled=state.page<=1;el('taskNext').disabled=state.page>=state.pages;el('taskListStatus').textContent=''; }).catch(function(err){if(id!==state.requestId)return;body.innerHTML='<tr class="u-empty-row"><td colspan="6" role="alert">'+esc(err.message||'Yuklashda xatolik')+'</td></tr>';el('taskListStatus').textContent='Topshiriqlarni yuklab bo‘lmadi.';}).then(function(){if(id===state.requestId)body.setAttribute('aria-busy','false');});
  }
  function renderRegions(t) { var active=new Set(taskRegions(t||{}).map(String));el('taskRegions').innerHTML=state.regions.map(function(r){var code=String(r.code||'');return '<label><input type="checkbox" value="'+esc(code)+'" '+(active.has(code)?'checked':'')+'> <span>'+esc(r.name_uz||r.name||code)+'</span></label>';}).join('')||'<span class="text-dim">Hududlar topilmadi.</span>'; }
  function loadRegions() { return NgoApi.get('/public/regions').then(function(r){state.regions=list(r.items);renderRegions();}); }
  function fileRows(files) { return list(files).map(function(item){return item&&item.file?item:{file:item,clientUploadId:uuid(),path:null,uploadId:null};}); }
  function renderSelected(files,target,kind) { el(target).innerHTML=list(files).map(function(row,index){var file=row.file;return '<div class="attachment"><span><strong>'+esc(file.name)+'</strong><small>'+esc(file.type||'Fayl')+' · '+esc(size(file.size))+'</small></span><span class="attachment__status">'+(row.path?'Yuklandi':'Tayyor')+'</span><button type="button" class="btn btn--sm btn--secondary" data-remove-file="'+esc(kind)+'" data-file-index="'+index+'">Olib tashlash</button></div>';}).join(''); }
  function setEditorFiles(files) { state.editorFiles=fileRows(files);renderSelected(state.editorFiles,'taskSelectedFiles','editor'); }
  function setDiscussionFiles(files) { state.discussionFiles=fileRows(files);renderSelected(state.discussionFiles,'taskDiscussionSelectedFiles','discussion'); }
  function uploadFiles(files,target) {
    var paths=[],chain=Promise.resolve();
    list(files).forEach(function(row,index){chain=chain.then(function(){var statuses=el(target).querySelectorAll('.attachment__status');if(row.path){paths.push(row.path);if(statuses[index])statuses[index].textContent='Yuklandi';return;}if(statuses[index])statuses[index].textContent='Yuklanmoqda: 0%';var file=row.file,form=new FormData();form.append('file',file,file.name);form.append('client_upload_id',row.clientUploadId);return NgoApi.upload('/admin/collaboration/upload',form,function(progress){if(statuses[index])statuses[index].textContent='Yuklanmoqda: '+progress+'%';}).then(function(result){if(!result||!result.path||!result.upload_id)throw new Error('Server fayl identifikatorini qaytarmadi.');row.path=result.path;row.uploadId=Number(result.upload_id);paths.push(row.path);if(statuses[index])statuses[index].textContent='Yuklandi';}).catch(function(error){if(statuses[index])statuses[index].textContent='Xatolik';throw error;});});});
    return chain.then(function(){return paths;});
  }
  function removePendingFile(kind,index,button) { var files=kind==='editor'?state.editorFiles:state.discussionFiles,row=files[index];if(!row)return;button.disabled=true;var discard=row.uploadId?NgoApi.del('/admin/collaboration/uploads/'+encodeURIComponent(row.uploadId)):Promise.resolve();discard.then(function(){files.splice(index,1);if(kind==='editor')setEditorFiles(files);else setDiscussionFiles(files);}).catch(function(error){button.disabled=false;toast(error.message||'Faylni olib tashlab bo‘lmadi. Qayta urinib ko‘ring.','error');}); }
  function editTask(t, opener) { t=t||{};el('taskEditorForm').reset();el('taskEditId').value=t.id||'';el('taskEditVersion').value=t.version||'';el('taskTitle').value=t.title||'';el('taskDescription').value=t.description||'';el('taskStartAt').value=localDate(t.scheduled_at);el('taskDueAt').value=localDate(t.due_at);el('taskConflict').hidden=true;el('taskEditorError').textContent='';el('taskFiles').disabled=Boolean(t.id);state.editorClientTaskId=t.id?null:uuid();setEditorFiles([]);if(t.id)el('taskSelectedFiles').innerHTML='<p class="text-dim">Yangi faylni topshiriq muhokamasida qo‘shing.</p>';renderRegions(t);open('taskEditor',opener); }
  function discussionAttachments(discussion){var found=[];list(discussion&&discussion.items).forEach(function(m){list(m.attachments).forEach(function(a){if(a.attachment_id!=null)found.push(a);});});return found;}
  function attachmentsHtml(items){return list(items).map(function(a){return '<div class="attachment"><span>'+esc(a.original_name||'Fayl')+'</span><button type="button" data-download="'+esc(a.attachment_id)+'" data-name="'+esc(a.original_name||'attachment')+'">Yuklab olish</button></div>';}).join('')||'<p class="text-dim">Muhokamada fayl yo‘q.</p>';}
  function messagesHtml(items){return list(items).map(function(m){return '<article class="message'+(m.mine?' message--mine':'')+'"><div class="message-meta">'+esc(m.sender_name||m.sender_email||'Admin')+' · '+esc(date(m.created_at))+'</div><div class="message-body">'+esc(m.body||'')+'</div>'+attachmentsHtml(m.attachments)+'</article>';}).join('')||'<p class="text-dim">Muhokama hali bo‘sh.</p>';}
  function renderDetail(t) { state.current=t;state.discussionRead=false;state.discussionClientMessageId=null;state.discussionDraftSignature=null;setDiscussionFiles([]);el('taskDetailTitle').textContent='#'+t.id+' '+t.title;el('taskDetailContent').innerHTML='<dl class="task-summary"><div><dt>Holat</dt><dd>'+esc(STATUS[t.status]||t.status)+'</dd></div><div><dt>Hududlar</dt><dd>'+esc(names(taskRegions(t)))+'</dd></div><div><dt>Boshlanishi</dt><dd>'+esc(date(t.scheduled_at))+'</dd></div><div><dt>Muddat</dt><dd>'+esc(date(t.due_at))+'</dd></div></dl>';el('taskOverviewPanel').innerHTML='<p>'+esc(t.description||'Tavsif yo‘q.')+'</p>';el('taskHistoryPanel').innerHTML=t.historyError?'<p role="alert">'+esc(t.historyError)+'</p>':'<ol class="collab-timeline">'+list(t.history).map(function(h){return '<li><strong>'+esc(h.actor_name||'Tizim')+'</strong> — '+esc(h.event_type)+'<br><small>'+esc(date(h.created_at))+'</small></li>';}).join('')+'</ol>';el('taskFilesPanel').innerHTML=t.discussionError?'<p role="alert">'+esc(t.discussionError)+'</p>':attachmentsHtml(discussionAttachments(t.discussion));el('taskDiscussionLog').innerHTML=t.discussionError?'<p role="alert">'+esc(t.discussionError)+'</p>':messagesHtml(t.discussion&&t.discussion.items);var allowed=list(t.allowed_actions),acts=allowedTransitions(t).map(function(a){return '<button type="button" class="btn btn--secondary" data-transition="'+esc(a)+'" data-task="'+esc(t.id)+'">'+esc(STATUS[a]||a)+'</button>';});if(allowed.indexOf('edit')>=0)acts.unshift('<button type="button" class="btn btn--secondary" data-edit-current>Tahrirlash</button>');if(allowed.indexOf('archive')>=0&&!t.archived_at)acts.push('<button type="button" class="btn btn--secondary" data-archive-task="'+esc(t.id)+'">Arxivlash</button>');if(t.discussion_thread_id)acts.push('<a class="btn btn--primary" href="admin-messages?thread_id='+encodeURIComponent(t.discussion_thread_id)+'&task_id='+encodeURIComponent(t.id)+'">To‘liq muhokama</a>');el('taskActions').innerHTML=acts.join(''); }
  function openTask(id, opener) { el('taskDetailContent').textContent='Yuklanmoqda...';open('taskDetail',opener);NgoApi.get('/admin/tasks/'+encodeURIComponent(id)).then(function(res){var t=res.item||res,history=NgoApi.get('/admin/tasks/'+encodeURIComponent(id)+'/events?limit=50').then(function(r){return r;},function(e){return{items:[],error:e.message||'Tarixni yuklab bo‘lmadi.'};}),discussion=t.discussion_thread_id?NgoApi.get('/admin/messages/threads/'+encodeURIComponent(t.discussion_thread_id)+'?limit=20').then(function(r){return r;},function(e){return{items:[],error:e.message||'Muhokamani yuklab bo‘lmadi.'};}):Promise.resolve({items:[]});return Promise.all([history,discussion]).then(function(extra){t.history=extra[0].items;t.historyError=extra[0].error;t.discussion=extra[1];t.discussionError=extra[1].error;renderDetail(t);});}).catch(function(err){el('taskDetailContent').innerHTML='<p role="alert">'+esc(err.message||'Topshiriqni yuklab bo‘lmadi.')+'</p>';}); }
  function beginTransition(id, action, opener){var t=state.current&&String(state.current.id)===String(id)?state.current:state.items.find(function(x){return String(x.id)===String(id);});state.transition={id:id,action:action,version:t&&t.version};el('transitionTitle').textContent=STATUS[action]||action;el('transitionHelp').textContent=(action==='blocked'||action==='done')?'Bu o‘tish uchun izoh majburiy.':'O‘zgarishni tasdiqlang.';el('transitionNote').required=action==='blocked'||action==='done';el('transitionNote').value='';el('transitionError').textContent='';open('transitionDialog',opener);}
  function saveTask(ev){ev.preventDefault();var id=el('taskEditId').value,p={version:el('taskEditVersion').value||null,title:el('taskTitle').value.trim(),description:el('taskDescription').value.trim(),region_codes:selected(el('taskRegions')).map(String),scheduled_at:el('taskStartAt').value||null,due_at:el('taskDueAt').value||null};if(!p.region_codes.length){el('taskEditorError').textContent='Kamida bitta hududni tanlang.';return;}el('taskSave').disabled=true;(id?Promise.resolve([]):uploadFiles(state.editorFiles,'taskSelectedFiles')).then(function(paths){if(!id){p.client_task_id=state.editorClientTaskId;p.attachment_paths=paths;p.attachment_caption=paths.length?'Topshiriqqa biriktirilgan hujjatlar':'';}return id?NgoApi.patch('/admin/tasks/'+encodeURIComponent(id),p):NgoApi.post('/admin/tasks',p);}).then(function(){close('taskEditor');state.editorClientTaskId=null;setEditorFiles([]);toast('Topshiriq saqlandi.','success');return loadTasks();}).catch(function(err){if(err.status===409){el('taskConflict').hidden=false;el('taskConflict').textContent='Bu identifikator boshqa topshiriq maʼlumotlari bilan ishlatilgan yoki topshiriq yangilangan. Maʼlumotlarni qayta tekshiring.';}el('taskEditorError').textContent=err.message||'Saqlashda xatolik';}).then(function(){el('taskSave').disabled=false;});}
  function downloadAttachment(id,name){NgoApi.download('/admin/collaboration/attachments/'+encodeURIComponent(id)).then(function(blob){var u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name||'attachment';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u);},1000);}).catch(function(err){toast(err.message||'Faylni yuklab bo‘lmadi.','error');});}
  document.addEventListener('click',function(ev){var c=ev.target.closest('[data-close-modal]');if(c){close(c.dataset.closeModal);return;}var remove=ev.target.closest('[data-remove-file]');if(remove){removePendingFile(remove.dataset.removeFile,Number(remove.dataset.fileIndex),remove);return;}var o=ev.target.closest('[data-task-open]');if(o){openTask(o.dataset.taskOpen,o);return;}var tr=ev.target.closest('[data-transition]');if(tr){beginTransition(tr.dataset.task,tr.dataset.transition,tr);return;}if(ev.target.closest('[data-edit-current]')){close('taskDetail');editTask(state.current,ev.target);return;}var archive=ev.target.closest('[data-archive-task]');if(archive){if(window.confirm('Topshiriq arxivlansinmi?')){archive.disabled=true;NgoApi.patch('/admin/tasks/'+encodeURIComponent(archive.dataset.archiveTask),{version:state.current.version,archived:true}).then(function(){close('taskDetail');toast('Topshiriq arxivlandi.','success');return loadTasks();}).catch(function(err){toast(err.status===409?'Topshiriq yangilangan; qayta oching.':err.message,'error');}).then(function(){archive.disabled=false;});}return;}var d=ev.target.closest('[data-download]');if(d)downloadAttachment(d.dataset.download,d.dataset.name);});
  document.querySelectorAll('.collab-tab').forEach(function(tab){tab.addEventListener('click',function(){document.querySelectorAll('.collab-tab').forEach(function(x){var active=x===tab;x.setAttribute('aria-selected',String(active));el(x.getAttribute('aria-controls')).hidden=!active;});if(tab.getAttribute('aria-controls')==='taskDiscussionPanel'&&!state.discussionRead&&state.current&&state.current.discussion_thread_id&&list(state.current.discussion&&state.current.discussion.items).length){var messages=state.current.discussion.items,last=messages[messages.length-1];state.discussionRead=true;NgoApi.post('/admin/messages/threads/'+encodeURIComponent(state.current.discussion_thread_id)+'/read',{message_id:last.id}).catch(function(){state.discussionRead=false;});}});});
  el('taskFilters').addEventListener('submit',function(ev){ev.preventDefault();state.page=1;loadTasks();});el('taskPageSize').addEventListener('change',function(){state.limit=Number(this.value);state.page=1;loadTasks();});el('taskPrev').addEventListener('click',function(){if(state.page>1){state.page--;loadTasks();}});el('taskNext').addEventListener('click',function(){if(state.page*state.limit<state.total){state.page++;loadTasks();}});el('newTaskBtn').addEventListener('click',function(ev){editTask(null,ev.currentTarget);});el('taskEditorForm').addEventListener('submit',saveTask);
  el('taskFiles').addEventListener('change',function(){setEditorFiles(Array.prototype.slice.call(this.files||[]));});el('taskDiscussionFiles').addEventListener('change',function(){setDiscussionFiles(Array.prototype.slice.call(this.files||[]));});
  el('transitionForm').addEventListener('submit',function(ev){ev.preventDefault();var note=el('transitionNote').value.trim(),p={version:state.transition.version,status:state.transition.action};if(p.status==='blocked')p.blocked_note=note;if(p.status==='done')p.completion_note=note;NgoApi.patch('/admin/tasks/'+encodeURIComponent(state.transition.id),p).then(function(){close('transitionDialog');close('taskDetail');toast('Holat yangilandi.','success');loadTasks();}).catch(function(err){el('transitionError').textContent=err.status===409?'Topshiriq yangilangan; sahifani yangilang.':err.message;});});
  el('taskDiscussionForm').addEventListener('submit',function(ev){ev.preventDefault();if(!state.current||!state.current.discussion_thread_id)return;var b=el('taskDiscussionBody'),body=b.value.trim();if(!body&&!state.discussionFiles.length)return;var submit=ev.submitter||ev.currentTarget.querySelector('[type="submit"]');submit.disabled=true;uploadFiles(state.discussionFiles,'taskDiscussionSelectedFiles').then(function(paths){var signature=JSON.stringify([body,paths]);if(state.discussionDraftSignature!==signature){state.discussionDraftSignature=signature;state.discussionClientMessageId=uuid();}return NgoApi.post('/admin/messages/threads/'+encodeURIComponent(state.current.discussion_thread_id),{body:body,client_message_id:state.discussionClientMessageId,attachments:paths});}).then(function(res){b.value='';state.discussionClientMessageId=null;state.discussionDraftSignature=null;setDiscussionFiles([]);var m=(res.item||res);state.current.discussion=state.current.discussion||{items:[]};if(!state.current.discussion.items.some(function(item){return String(item.id)===String(m.id);}))state.current.discussion.items.push(m);el('taskDiscussionLog').innerHTML=messagesHtml(state.current.discussion.items);el('taskFilesPanel').innerHTML=attachmentsHtml(discussionAttachments(state.current.discussion));}).catch(function(err){toast(err.message||'Xabarni yuborib bo‘lmadi.','error');}).then(function(){submit.disabled=false;});});
  function init(){var u=window.__CURRENT_USER__||(NgoApi.getUser&&NgoApi.getUser())||{},params=new URLSearchParams(location.search),status=params.get('status');state.user=u;if(u.role==='super_admin')el('newTaskBtn').hidden=false;Array.prototype.forEach.call(el('taskStatus').options,function(option){if(option.value===status)el('taskStatus').value=status;});if(params.get('due')==='overdue')state.due='overdue';Promise.all([loadRegions(),loadTasks()]).then(function(){var id=params.get('task_id');if(id)openTask(id,el('tasksTableTitle'));else if(params.get('action')==='new'&&u.role==='super_admin')editTask(null,el('newTaskBtn'));});}
  (function wait(n){if(window.__CURRENT_USER__||!n)init();else setTimeout(function(){wait(n-1);},100);})(30);
})();
