/* Task collaboration UI. API contract is documented in COLLABORATION_FRONTEND_API.md. */
(function () {
  'use strict';
  var state = { page: 1, pages: 1, limit: 20, total: 0, items: [], current: null, user: {}, options: { users: [], regions: [], labels: [] }, transition: null, requestId: 0, due: '', discussionRead: false };
  var STATUS = { new:'Yangi', in_progress:'Jarayonda', blocked:'Bloklangan', done:'Bajarilgan', cancelled:'Bekor qilingan', archived:'Arxivlangan' };
  var PRIORITY = { low:'Past', normal:'Oddiy', high:'Yuqori', urgent:'Shoshilinch' };
  var BADGE = { new:'warning', in_progress:'info', blocked:'error', done:'success', cancelled:'neutral', archived:'neutral' };
  function el(id) { return document.getElementById(id); }
  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
  function list(v) { return Array.isArray(v) ? v : []; }
  function names(v, fallback) { var a = list(v).map(function(x){ return typeof x === 'string' ? x : (x.full_name || x.name || x.email || x.code); }).filter(Boolean); return a.length ? a.join(', ') : (fallback || '—'); }
  function date(v) { if (!v) return '—'; var d = new Date(v); return isNaN(d.getTime()) ? String(v) : d.toLocaleString(); }
  function localDate(v) { if (!v) return ''; var d = new Date(v); if (isNaN(d.getTime())) return ''; return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16); }
  function toast(message, type) { var n=el('cmsToast'); if(!n)return; n.textContent=message; n.className='cms-toast cms-toast--'+(type||'info')+' show'; setTimeout(function(){n.classList.remove('show');},4000); }
  function close(id) { if (window.AdminModal) AdminModal.close(id); }
  function open(id, opener) { if (window.AdminModal) AdminModal.open(id, opener); }
  function selected(container) { return Array.prototype.map.call(container.querySelectorAll('input:checked'),function(i){return Number(i.value)||i.value;}); }
  function uuid() { var c=window.crypto||window.msCrypto;if(c&&c.randomUUID)return c.randomUUID();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(ch){var r=c&&c.getRandomValues?c.getRandomValues(new Uint8Array(1))[0]&15:Math.floor(Math.random()*16),v=ch==='x'?r:(r&3|8);return v.toString(16);}); }
  function query() {
    var sort=el('taskSort').value.split('_'),direction=sort.pop(),field=sort.join('_');
    if(field==='due')field='due_at';
    if(field==='created')field='created_at';
    var p = new URLSearchParams({ page:String(state.page), limit:String(state.limit), sort:field, direction:direction });
    [['q','taskQuery'],['status','taskStatus'],['priority','taskPriorityFilter']].forEach(function(x){var v=el(x[1]).value.trim();if(v)p.set(x[0],v);});
    if(state.due)p.set('due',state.due);
    return p.toString();
  }
  function renderKpis(k) { k=k||{}; el('taskKpiOpen').textContent=Number(k.new_count||0)+Number(k.in_progress_count||0)+Number(k.blocked_count||0); el('taskKpiOverdue').textContent=k.overdue_count||0; el('taskKpiBlocked').textContent=k.blocked_count||0; el('taskKpiDone').textContent=k.done_count||0; }
  function taskUsers(t) { return list(t.assignees).length ? t.assignees : (t.assignee ? [t.assignee] : []); }
  function taskRegions(t) { return list(t.regions).length ? t.regions : (t.assigned_region_code ? [t.assigned_region_code] : []); }
  function allowedTransitions(t) { if (list(t.allowed_actions).indexOf('transition') === -1) return []; var m={new:['in_progress','cancelled'],in_progress:['blocked','done','cancelled'],blocked:['in_progress','cancelled'],done:['in_progress'],cancelled:['new']};return m[t.status]||[]; }
  function renderRows() {
    var body=el('tasksTableRows');
    if(!state.items.length){body.innerHTML='<tr class="u-empty-row"><td colspan="8" role="status">Topshiriq topilmadi.</td></tr>';return;}
    body.innerHTML=state.items.map(function(t){
      var actions=allowedTransitions(t).slice(0,2).map(function(a){return '<button type="button" class="btn btn--sm btn--secondary" data-transition="'+esc(a)+'" data-task="'+esc(t.id)+'">'+esc(STATUS[a]||a)+'</button>';}).join(' ');
      return '<tr><td>#'+esc(t.id)+'</td><td><button class="task-link" type="button" data-task-open="'+esc(t.id)+'">'+esc(t.title)+'</button><br><span class="text-dim">'+esc(names(t.labels))+'</span></td><td>'+esc(names(taskUsers(t),'Hudud bo‘yicha'))+'</td><td>'+esc(names(taskRegions(t)))+'</td><td>'+esc(date(t.due_at))+(t.due_state==='overdue'?' <span class="badge badge--error">Kechikdi</span>':'')+'</td><td>'+esc(PRIORITY[t.priority]||t.priority||'—')+'</td><td><span class="badge badge--'+(BADGE[t.status]||'neutral')+'">'+esc(STATUS[t.status]||t.status)+'</span></td><td><button type="button" class="btn btn--sm btn--secondary" data-task-open="'+esc(t.id)+'">Ko‘rish</button> '+actions+'</td></tr>';
    }).join('');
  }
  function loadTasks() {
    var id=++state.requestId, body=el('tasksTableRows'); body.setAttribute('aria-busy','true'); el('taskListStatus').textContent='Yuklanmoqda...';
    return NgoApi.get('/admin/tasks?'+query()).then(function(res){ if(id!==state.requestId)return; state.items=list(res.items);state.total=Number(res.total||state.items.length);state.pages=Number(res.pages||Math.max(1,Math.ceil(state.total/state.limit)));renderRows();renderKpis(res.kpis);el('taskTotal').textContent=state.total+' ta';el('taskPageInfo').textContent=state.page+' / '+state.pages;el('taskPrev').disabled=state.page<=1;el('taskNext').disabled=state.page>=state.pages;el('taskListStatus').textContent=''; }).catch(function(err){if(id!==state.requestId)return;body.innerHTML='<tr class="u-empty-row"><td colspan="8" role="alert">'+esc(err.message||'Yuklashda xatolik')+'</td></tr>';el('taskListStatus').textContent='Topshiriqlarni yuklab bo‘lmadi.';}).then(function(){if(id===state.requestId)body.setAttribute('aria-busy','false');});
  }
  function renderChecks(target, items, selectedIds, label) { var set=new Set(list(selectedIds).map(String)); el(target).innerHTML=list(items).map(function(x){var id=x.id==null?x.code:x.id;return '<label><input type="checkbox" value="'+esc(id)+'" '+(set.has(String(id))?'checked':'')+'> <span>'+esc(label(x))+'</span></label>';}).join('')||'<span class="text-dim">Ma’lumot yo‘q</span>'; }
  function loadOptions() { return Promise.all([NgoApi.get('/admin/messages/users'),NgoApi.get('/public/regions'),NgoApi.get('/admin/tasks/labels')]).then(function(r){state.options.users=list(r[0].items);state.options.regions=list(r[1].items);state.options.labels=list(r[2].items);fillEditor();}); }
  function fillEditor(t) { t=t||{}; renderChecks('taskAssignees',state.options.users.filter(function(u){return u.role==='regional_admin';}),list(t.assignees).map(function(x){return x.id;}),function(u){return (u.full_name||u.email)+(u.region_code?' — '+u.region_code:'');});renderChecks('taskWatchers',state.options.users,list(t.watchers).map(function(x){return x.id;}),function(u){return u.full_name||u.email;});renderChecks('taskRegions',state.options.regions,list(t.regions),function(r){return r.name_uz||r.name||r.code;});renderChecks('taskLabels',state.options.labels,list(t.labels).map(function(x){return x.id;}),function(x){return x.name;}); }
  function editTask(t, opener) { t=t||{};el('taskEditorForm').reset();el('taskEditId').value=t.id||'';el('taskEditVersion').value=t.version||'';el('taskTitle').value=t.title||'';el('taskDescription').value=t.description||'';el('taskStartAt').value=localDate(t.scheduled_at);el('taskDueAt').value=localDate(t.due_at);el('taskPriority').value=t.priority||'normal';el('taskProgress').value=t.progress||0;el('taskConflict').hidden=true;el('taskEditorError').textContent='';fillEditor(t);open('taskEditor',opener); }
  function discussionAttachments(discussion){var found=[];list(discussion&&discussion.items).forEach(function(m){list(m.attachments).forEach(function(a){if(a.attachment_id!=null)found.push(a);});});return found;}
  function attachmentsHtml(items){return list(items).map(function(a){return '<div class="attachment"><span>'+esc(a.original_name||'Fayl')+'</span><button type="button" data-download="'+esc(a.attachment_id)+'" data-name="'+esc(a.original_name||'attachment')+'">Yuklab olish</button></div>';}).join('')||'<p class="text-dim">Muhokamada fayl yo‘q.</p>';}
  function messagesHtml(items){return list(items).map(function(m){return '<article class="message'+(m.mine?' message--mine':'')+'"><div class="message-meta">'+esc(m.sender_name||m.sender_email||'Admin')+' · '+esc(date(m.created_at))+'</div><div class="message-body">'+esc(m.body)+'</div></article>';}).join('')||'<p class="text-dim">Muhokama hali bo‘sh.</p>';}
  function renderDetail(t) { state.current=t;state.discussionRead=false;el('taskDetailTitle').textContent='#'+t.id+' '+t.title;el('taskDetailContent').innerHTML='<dl class="task-summary"><div><dt>Holat</dt><dd>'+esc(STATUS[t.status]||t.status)+'</dd></div><div><dt>Muhimlik</dt><dd>'+esc(PRIORITY[t.priority]||t.priority)+'</dd></div><div><dt>Taraqqiyot</dt><dd>'+esc(t.progress||0)+'%</dd></div><div><dt>Mas’ullar</dt><dd>'+esc(names(taskUsers(t)))+'</dd></div><div><dt>Hududlar</dt><dd>'+esc(names(taskRegions(t)))+'</dd></div><div><dt>Muddat</dt><dd>'+esc(date(t.due_at))+'</dd></div></dl>';el('taskOverviewPanel').innerHTML='<p>'+esc(t.description||'Tavsif yo‘q.')+'</p><div class="chip-list">'+list(t.labels).map(function(x){return '<span class="collab-chip" style="border-color:'+esc(x.color||'#64748b')+'">'+esc(x.name)+'</span>';}).join('')+'</div>';el('taskHistoryPanel').innerHTML=t.historyError?'<p role="alert">'+esc(t.historyError)+'</p>':'<ol class="collab-timeline">'+list(t.history).map(function(h){return '<li><strong>'+esc(h.actor_name||'Tizim')+'</strong> — '+esc(h.event_type)+'<br><small>'+esc(date(h.created_at))+'</small></li>';}).join('')+'</ol>';el('taskFilesPanel').innerHTML=t.discussionError?'<p role="alert">'+esc(t.discussionError)+'</p>':attachmentsHtml(discussionAttachments(t.discussion));el('taskDiscussionLog').innerHTML=t.discussionError?'<p role="alert">'+esc(t.discussionError)+'</p>':messagesHtml(t.discussion&&t.discussion.items);var allowed=list(t.allowed_actions),acts=allowedTransitions(t).map(function(a){return '<button type="button" class="btn btn--secondary" data-transition="'+esc(a)+'" data-task="'+esc(t.id)+'">'+esc(STATUS[a]||a)+'</button>';});if(allowed.indexOf('edit')>=0)acts.unshift('<button type="button" class="btn btn--secondary" data-edit-current>Tahrirlash</button>');if(allowed.indexOf('watch')>=0){var watching=list(t.watchers).some(function(w){return String(w.id)===String(state.user.id);});acts.push('<button type="button" class="btn btn--secondary" data-watch-task="'+esc(t.id)+'" data-watching="'+(watching?'1':'0')+'">'+(watching?'Kuzatishni to‘xtatish':'Kuzatish')+'</button>');}if(allowed.indexOf('archive')>=0&&!t.archived_at)acts.push('<button type="button" class="btn btn--secondary" data-archive-task="'+esc(t.id)+'">Arxivlash</button>');if(t.discussion_thread_id)acts.push('<a class="btn btn--primary" href="admin-messages?thread_id='+encodeURIComponent(t.discussion_thread_id)+'&task_id='+encodeURIComponent(t.id)+'">To‘liq muhokama</a>');el('taskActions').innerHTML=acts.join(''); }
  function openTask(id, opener) { el('taskDetailContent').textContent='Yuklanmoqda...';open('taskDetail',opener);NgoApi.get('/admin/tasks/'+encodeURIComponent(id)).then(function(res){var t=res.item||res,history=NgoApi.get('/admin/tasks/'+encodeURIComponent(id)+'/events?limit=50').then(function(r){return r;},function(e){return{items:[],error:e.message||'Tarixni yuklab bo‘lmadi.'};}),discussion=t.discussion_thread_id?NgoApi.get('/admin/messages/threads/'+encodeURIComponent(t.discussion_thread_id)+'?limit=20').then(function(r){return r;},function(e){return{items:[],error:e.message||'Muhokamani yuklab bo‘lmadi.'};}):Promise.resolve({items:[]});return Promise.all([history,discussion]).then(function(extra){t.history=extra[0].items;t.historyError=extra[0].error;t.discussion=extra[1];t.discussionError=extra[1].error;renderDetail(t);});}).catch(function(err){el('taskDetailContent').innerHTML='<p role="alert">'+esc(err.message||'Topshiriqni yuklab bo‘lmadi.')+'</p>';}); }
  function beginTransition(id, action, opener){var t=state.current&&String(state.current.id)===String(id)?state.current:state.items.find(function(x){return String(x.id)===String(id);});state.transition={id:id,action:action,version:t&&t.version};el('transitionTitle').textContent=STATUS[action]||action;el('transitionHelp').textContent=(action==='blocked'||action==='done')?'Bu o‘tish uchun izoh majburiy.':'O‘zgarishni tasdiqlang.';el('transitionNote').required=action==='blocked'||action==='done';el('transitionNote').value='';el('transitionError').textContent='';open('transitionDialog',opener);}
  function saveTask(ev){ev.preventDefault();var id=el('taskEditId').value,p={version:el('taskEditVersion').value||null,title:el('taskTitle').value.trim(),description:el('taskDescription').value.trim(),assignee_user_ids:selected(el('taskAssignees')),region_codes:selected(el('taskRegions')).map(String),watcher_user_ids:selected(el('taskWatchers')),label_ids:selected(el('taskLabels')).map(Number),scheduled_at:el('taskStartAt').value||null,due_at:el('taskDueAt').value||null,priority:el('taskPriority').value,progress:Number(el('taskProgress').value||0)};el('taskSave').disabled=true;(id?NgoApi.patch('/admin/tasks/'+encodeURIComponent(id),p):NgoApi.post('/admin/tasks',p)).then(function(){close('taskEditor');toast('Topshiriq saqlandi.','success');return loadTasks();}).catch(function(err){if(err.status===409){el('taskConflict').hidden=false;el('taskConflict').textContent='Bu topshiriq boshqa foydalanuvchi tomonidan yangilangan. Yangilangan nusxani oching va o‘zgarishlarni qayta kiriting.';}el('taskEditorError').textContent=err.message||'Saqlashda xatolik';}).then(function(){el('taskSave').disabled=false;});}
  function downloadAttachment(id,name){NgoApi.download('/admin/collaboration/attachments/'+encodeURIComponent(id)).then(function(blob){var u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name||'attachment';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u);},1000);}).catch(function(err){toast(err.message||'Faylni yuklab bo‘lmadi.','error');});}
  document.addEventListener('click',function(ev){var c=ev.target.closest('[data-close-modal]');if(c){close(c.dataset.closeModal);return;}var o=ev.target.closest('[data-task-open]');if(o){openTask(o.dataset.taskOpen,o);return;}var tr=ev.target.closest('[data-transition]');if(tr){beginTransition(tr.dataset.task,tr.dataset.transition,tr);return;}if(ev.target.closest('[data-edit-current]')){close('taskDetail');editTask(state.current,ev.target);return;}var watch=ev.target.closest('[data-watch-task]');if(watch){var shouldWatch=watch.dataset.watching!=='1';watch.disabled=true;NgoApi.post('/admin/tasks/'+encodeURIComponent(watch.dataset.watchTask)+'/watch',{watch:shouldWatch}).then(function(){state.current.watchers=shouldWatch?list(state.current.watchers).concat([state.user]):list(state.current.watchers).filter(function(u){return String(u.id)!==String(state.user.id);});renderDetail(state.current);toast(shouldWatch?'Kuzatuv yoqildi.':'Kuzatuv o‘chirildi.','success');}).catch(function(err){toast(err.message||'Kuzatuvni o‘zgartirib bo‘lmadi.','error');}).then(function(){watch.disabled=false;});return;}var archive=ev.target.closest('[data-archive-task]');if(archive){if(window.confirm('Topshiriq arxivlansinmi?')){archive.disabled=true;NgoApi.patch('/admin/tasks/'+encodeURIComponent(archive.dataset.archiveTask),{version:state.current.version,archived:true}).then(function(){close('taskDetail');toast('Topshiriq arxivlandi.','success');return loadTasks();}).catch(function(err){toast(err.status===409?'Topshiriq yangilangan; qayta oching.':err.message,'error');}).then(function(){archive.disabled=false;});}return;}var d=ev.target.closest('[data-download]');if(d)downloadAttachment(d.dataset.download,d.dataset.name);});
  document.querySelectorAll('.collab-tab').forEach(function(tab){tab.addEventListener('click',function(){document.querySelectorAll('.collab-tab').forEach(function(x){var active=x===tab;x.setAttribute('aria-selected',String(active));el(x.getAttribute('aria-controls')).hidden=!active;});if(tab.getAttribute('aria-controls')==='taskDiscussionPanel'&&!state.discussionRead&&state.current&&state.current.discussion_thread_id&&list(state.current.discussion&&state.current.discussion.items).length){var messages=state.current.discussion.items,last=messages[messages.length-1];state.discussionRead=true;NgoApi.post('/admin/messages/threads/'+encodeURIComponent(state.current.discussion_thread_id)+'/read',{message_id:last.id}).catch(function(){state.discussionRead=false;});}});});
  el('taskFilters').addEventListener('submit',function(ev){ev.preventDefault();state.page=1;loadTasks();});el('taskPageSize').addEventListener('change',function(){state.limit=Number(this.value);state.page=1;loadTasks();});el('taskPrev').addEventListener('click',function(){if(state.page>1){state.page--;loadTasks();}});el('taskNext').addEventListener('click',function(){if(state.page*state.limit<state.total){state.page++;loadTasks();}});el('newTaskBtn').addEventListener('click',function(ev){editTask(null,ev.currentTarget);});el('taskEditorForm').addEventListener('submit',saveTask);
  el('transitionForm').addEventListener('submit',function(ev){ev.preventDefault();var note=el('transitionNote').value.trim(),p={version:state.transition.version,status:state.transition.action};if(p.status==='blocked')p.blocked_note=note;if(p.status==='done')p.completion_note=note;NgoApi.patch('/admin/tasks/'+encodeURIComponent(state.transition.id),p).then(function(){close('transitionDialog');close('taskDetail');toast('Holat yangilandi.','success');loadTasks();}).catch(function(err){el('transitionError').textContent=err.status===409?'Topshiriq yangilangan; sahifani yangilang.':err.message;});});
  el('taskDiscussionForm').addEventListener('submit',function(ev){ev.preventDefault();if(!state.current||!state.current.discussion_thread_id)return;var b=el('taskDiscussionBody'),body=b.value.trim();if(!body)return;NgoApi.post('/admin/messages/threads/'+encodeURIComponent(state.current.discussion_thread_id),{body:body,client_message_id:uuid(),attachments:[]}).then(function(res){b.value='';var m=(res.item||res);state.current.discussion=state.current.discussion||{items:[]};state.current.discussion.items.push(m);el('taskDiscussionLog').innerHTML=messagesHtml(state.current.discussion.items);el('taskFilesPanel').innerHTML=attachmentsHtml(discussionAttachments(state.current.discussion));}).catch(function(err){toast(err.message||'Xabarni yuborib bo‘lmadi.','error');});});
  function init(){var u=window.__CURRENT_USER__||(NgoApi.getUser&&NgoApi.getUser())||{},params=new URLSearchParams(location.search),status=params.get('status'),priority=params.get('priority');state.user=u;if(u.role==='super_admin')el('newTaskBtn').hidden=false;Array.prototype.forEach.call(el('taskStatus').options,function(option){if(option.value===status)el('taskStatus').value=status;});Array.prototype.forEach.call(el('taskPriorityFilter').options,function(option){if(option.value===priority)el('taskPriorityFilter').value=priority;});if(params.get('due')==='overdue')state.due='overdue';Promise.all([loadOptions(),loadTasks()]).then(function(){var id=params.get('task_id');if(id)openTask(id,el('tasksTableTitle'));else if(params.get('action')==='new'&&u.role==='super_admin')editTask(null,el('newTaskBtn'));});}
  (function wait(n){if(window.__CURRENT_USER__||!n)init();else setTimeout(function(){wait(n-1);},100);})(30);
})();
